server:
  port: 8081
  servlet:
    context-path: /pre
# dev 开发环境 prod 线上环境
spring:
  application:
    name: pre
  profiles:
    active: dev
  servlet:
    multipart:
      # 根据实际需求作调整
      # 默认最大上传文件大小为1M，单个文件大小
      max-file-size: 10MB
      # 默认最大请求大小为10M，总上传的数据大小
      max-request-size: 15MB
